### ISSUE TITLE
Error when try run the application

### ISSUE THREAD

**Issue by guicunha** [fireship-io/google-sheets-database#1]
`error - ./node_modules/google-auth-library/build/src/auth/googleauth.js:17:0
Module not found: Can't resolve 'child_process'
null
Error: `props.dangerouslySetInnerHTML` must be in the form `{__html: ...}`. Please visit https://reactjs.org/link/dangerously-set-inner-html for more information.
    at assertValidProps (C:\Users\Guilherme\Documents\gsheet-api\holy-sheet\node_modules\react-dom\cjs\react-dom-server.node.development.js:1828:15)
    at ReactDOMServerRenderer.renderDOM (C:\Users\Guilherme\Documents\gsheet-api\holy-sheet\node_modules\react-dom\cjs\react-dom-server.node.development.js:4231:5)
    at ReactDOMServerRenderer.render (C:\Users\Guilherme\Documents\gsheet-api\holy-sheet\node_modules\react-dom\cjs\react-dom-server.node.development.js:3802:21)
    at ReactDOMServerRenderer.read (C:\Users\Guilherme\Documents\gsheet-api\holy-sheet\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at renderToString (C:\Users\Guilherme\Documents\gsheet-api\holy-sheet\node_modules\react-dom\cjs\react-dom-server.node.development.js:4298:27)
    at Object.renderPage (C:\Users\Guilherme\Documents\gsheet-api\holy-sheet\node_modules\next\dist\next-server\server\render.js:53:854)
    at Function.getInitialProps (C:\Users\Guilherme\Documents\gsheet-api\holy-sheet\.next\server\pages\_document.js:625:19)
    at loadGetInitialProps (C:\Users\Guilherme\Documents\gsheet-api\holy-sheet\node_modules\next\dist\next-server\lib\utils.js:5:101)
    at renderToHTML (C:\Users\Guilherme\Documents\gsheet-api\holy-sheet\node_modules\next\dist\next-server\server\render.js:53:1145)
    at runMicrotasks (<anonymous>)
`

**Comment by guicunha** [comment]
Solved, i add the file secrets.json on my auth.getclient

```
    const auth = await google.auth.getClient({
        keyFilename: './secrets.json',
        scopes: ['https://www.googleapis.com/auth/spreadsheets.readonly']
    });
```
